<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="<?= BASE_URL ?>css/discos.css"> 
    <title>Discos</title>
</head>
<body>
   <div class="catalogo">

    <?php foreach ($discos as $disco): ?>

    <div class="card-disco">

        <a href="<?= BASE_URL ?>disco/<?= $disco->id ?>">
            <div class="disco">
                
                <img
                    src="<?= BASE_URL ?>images/<?=$disco->id?>.jpg"
                    alt="<?=$disco->titulo?>"
                >

                <div class="titulo">
                    <h3><?=$disco->titulo?></h3>
                </div>

            </div>

        </a>

        <form
            action="<?= BASE_URL ?>addColeccion"
            method="POST"
        >

            <input
                type="hidden"
                name="id_disco"
                value="<?=$disco->id?>"
            >

            <button type="submit">
                agregar
            </button>

        </form>

    </div>

    <?php endforeach; ?>

</div>
    
</body>
</html>