<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="login-container">
        <h1>Iniciar Sesión</h1>
        <form action="<?=BASE_URL ?>login" method="POST" class="login">
            <label for="nombre">Usuario</label>
            <input type="text" name="nombre"  required>

            <label for="contraseña">contraseña</label>
            <input type="password" name="contraseña" required>

            <button type="submit">Iniciar Sesión</button>

            <?php if(!empty($error)):?>
                <p class="error"><?= htmlspecialchars($error) ?></p>
            <?php endif; ?>
            </form>
            
        </login-form>

    </div>
</body>
</html>