<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel = "Stylesheet" href="<?= BASE_URL ?>css/miColeccion.css">
    <title>Discos</title>
</head>
<body>
   <div class="catalogo">

    <?php foreach ($discos as $disco): ?>

        <a href="<?= BASE_URL ?>disco/<?= $disco->id ?>">

            <div class="disco">

                <img
                    src="images/<?=$disco->id?>.jpg"
                    alt="<?=$disco->titulo?>"
                >

                <div class="titulo">
                    <h3><?=$disco->titulo?></h3>
                </div>

            </div>

        </a>



    <?php endforeach; ?>

</div>
    
</body>
</html>